
services:
  db:
    container_name: database
    image: postgres:16.4
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-db}"
      POSTGRES_USER: "${POSTGRES_USER:-root}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-root}"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-db}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    container_name: backend
    image: vstableages/backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: "${DB_HOST:-db}"
      DB_SCHEMA: "${DB_SCHEMA:-db}"
      DB_USERNAME: "${DB_USERNAME:-root}"
      DB_PASSWORD: "${DB_PASSWORD:-root}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILE:-dev}"
      DATABASE_DDL: "update"
      SPRING_SERVER_PORT: 8070
      AVENIA_BASE_URL: "${AVENIA_BASE_URL:-https://api.sandbox.avenia.io:10952}"
      AVENIA_API_KEY: "${AVENIA_API_KEY:-}"
      AVENIA_PRIVATE_KEY: "${AVENIA_PRIVATE_KEY:-}"
    ports:
      - "8070:8070"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres:
