spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:db}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  idempotency:
    secret: ${IDEMPOTENCY_HASH_SECRET:troque-este-segredo-em-producao}
api:
  auth:
    jwt:
      secret: ${JWT_SECRET:lR4kEZSOXyCXvzbmgrfLAmSWKtHJnCZ6fJLp5Pm/980a5xogpjaahKGuLPou8P8647IQthO/iX61VWueFl00hA==}
    header:
      name: X-AUTH-API-SECRET-KEY