-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.administradores
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    nome_completo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(20) COLLATE pg_catalog."default",
    cargo character varying(100) COLLATE pg_catalog."default",
    hash_senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nivel_acesso nivel_acesso_admin_enum DEFAULT 'SUPER_ADMIN'::nivel_acesso_admin_enum,
    exigir_2fa boolean DEFAULT true,
    troca_senha_obrigatoria boolean DEFAULT true,
    alerta_novo_acesso boolean DEFAULT true,
    ativo boolean DEFAULT true,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT administradores_pkey PRIMARY KEY (id),
    CONSTRAINT administradores_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.beneficiarios
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    empresa_id uuid NOT NULL,
    avenia_id uuid,
    avenia_wallet_id uuid,
    apelido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    descricao_interna character varying(255) COLLATE pg_catalog."default",
    tipo_recebimento tipo_recebimento_enum NOT NULL DEFAULT 'CONTA_BANCARIA'::tipo_recebimento_enum,
    chave_pix character varying(255) COLLATE pg_catalog."default",
    documento_identificacao character varying(20) COLLATE pg_catalog."default",
    nome_titular character varying(255) COLLATE pg_catalog."default",
    codigo_banco character varying(10) COLLATE pg_catalog."default",
    agencia character varying(20) COLLATE pg_catalog."default",
    numero_conta character varying(50) COLLATE pg_catalog."default",
    tipo_conta tipo_conta_bancaria_enum,
    pais character varying(100) COLLATE pg_catalog."default",
    rede_blockchain rede_blockchain_enum,
    endereco_wallet character varying(120) COLLATE pg_catalog."default",
    wallet_memo character varying(100) COLLATE pg_catalog."default",
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT beneficiarios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.documentos_compliance
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    empresa_id uuid NOT NULL,
    tipo_documento tipo_documento_enum NOT NULL,
    nome_arquivo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    url_arquivo text COLLATE pg_catalog."default" NOT NULL,
    tamanho_arquivo_bytes bigint,
    status status_compliance_enum DEFAULT 'EM_ANALISE'::status_compliance_enum,
    enviado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT documentos_compliance_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empresas
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    razao_social character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    cnpj character varying(18) COLLATE pg_catalog."default" NOT NULL,
    pais character varying(100) COLLATE pg_catalog."default" DEFAULT 'Brasil'::character varying,
    cep character varying(20) COLLATE pg_catalog."default",
    cidade character varying(100) COLLATE pg_catalog."default",
    estado character varying(50) COLLATE pg_catalog."default",
    atividade_principal character varying(255) COLLATE pg_catalog."default",
    proposito_conta character varying(255) COLLATE pg_catalog."default",
    finalidade_transacoes character varying(255) COLLATE pg_catalog."default",
    receita_anual_estimada character varying(100) COLLATE pg_catalog."default",
    origem_recursos character varying(255) COLLATE pg_catalog."default",
    status_kyb status_compliance_enum DEFAULT 'PENDENTE'::status_compliance_enum,
    status_aml status_compliance_enum DEFAULT 'PENDENTE'::status_compliance_enum,
    kyc_usd_aprovado boolean DEFAULT false,
    kyc_cop_aprovado boolean DEFAULT false,
    saldo_disponivel_brl numeric(15, 2) DEFAULT 0.00,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT empresas_pkey PRIMARY KEY (id),
    CONSTRAINT empresas_cnpj_key UNIQUE (cnpj)
);

CREATE TABLE IF NOT EXISTS public.progresso_cadastros
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    usuario_id uuid NOT NULL,
    etapa_pendente etapa_pendente_enum DEFAULT 'DADOS_FINANCEIROS_EMPRESA'::etapa_pendente_enum,
    status_geral status_onboarding_enum DEFAULT 'AGUARDANDO_DADOS'::status_onboarding_enum,
    status_compliance_final status_compliance_enum DEFAULT 'PENDENTE'::status_compliance_enum,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT progresso_cadastros_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.transacoes_base
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    empresa_id uuid NOT NULL,
    usuario_criador_id uuid,
    status status_transacao_enum DEFAULT 'PROCESSANDO'::status_transacao_enum,
    moeda_estrangeira character varying(3) COLLATE pg_catalog."default" NOT NULL,
    valor_estrangeiro numeric(15, 2) NOT NULL,
    valor_liquidacao_brl numeric(15, 2),
    taxa_servico_brl numeric(10, 2) DEFAULT 0.00,
    percentual_spread_efetivo numeric(5, 4),
    taxa_cambio numeric(12, 6),
    avenia_ticket_id uuid,
    hash_transacao_blockchain character varying(120) COLLATE pg_catalog."default",
    liquidado_em timestamp with time zone,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transacoes_base_pkey PRIMARY KEY (id),
    CONSTRAINT transacoes_base_avenia_ticket_id_key UNIQUE (avenia_ticket_id)
);

CREATE TABLE IF NOT EXISTS public.transacoes_exportacao
(
    transacao_id uuid NOT NULL,
    codigo_cobranca_externa character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome_pagador_externo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email_pagador_externo character varying(255) COLLATE pg_catalog."default",
    data_vencimento date NOT NULL,
    descricao_motivo text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT transacoes_exportacao_pkey PRIMARY KEY (transacao_id),
    CONSTRAINT transacoes_exportacao_codigo_cobranca_externa_key UNIQUE (codigo_cobranca_externa)
);

CREATE TABLE IF NOT EXISTS public.transacoes_importacao
(
    transacao_id uuid NOT NULL,
    beneficiario_id uuid NOT NULL,
    metodo_transferencia metodo_transferencia_enum NOT NULL,
    CONSTRAINT transacoes_importacao_pkey PRIMARY KEY (transacao_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    empresa_id uuid NOT NULL,
    nome_completo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cpf character varying(14) COLLATE pg_catalog."default",
    data_nascimento date,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(20) COLLATE pg_catalog."default",
    cargo character varying(100) COLLATE pg_catalog."default",
    pais_residencia character varying(100) COLLATE pg_catalog."default" DEFAULT 'Brasil'::character varying,
    hash_senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    segredo_2fa character varying(100) COLLATE pg_catalog."default",
    habilitado_2fa boolean DEFAULT false,
    ativo boolean DEFAULT true,
    criado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    atualizado_em timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_cpf_key UNIQUE (cpf),
    CONSTRAINT usuarios_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.beneficiarios
    ADD CONSTRAINT beneficiarios_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_beneficiarios_empresa
    ON public.beneficiarios(empresa_id);


ALTER TABLE IF EXISTS public.documentos_compliance
    ADD CONSTRAINT documentos_compliance_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.progresso_cadastros
    ADD CONSTRAINT progresso_cadastros_usuario_id_fkey FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_progresso_usuario
    ON public.progresso_cadastros(usuario_id);


ALTER TABLE IF EXISTS public.transacoes_base
    ADD CONSTRAINT transacoes_base_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_transacoes_base_empresa
    ON public.transacoes_base(empresa_id);


ALTER TABLE IF EXISTS public.transacoes_base
    ADD CONSTRAINT transacoes_base_usuario_criador_id_fkey FOREIGN KEY (usuario_criador_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.transacoes_exportacao
    ADD CONSTRAINT transacoes_exportacao_transacao_id_fkey FOREIGN KEY (transacao_id)
    REFERENCES public.transacoes_base (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS transacoes_exportacao_pkey
    ON public.transacoes_exportacao(transacao_id);


ALTER TABLE IF EXISTS public.transacoes_importacao
    ADD CONSTRAINT transacoes_importacao_beneficiario_id_fkey FOREIGN KEY (beneficiario_id)
    REFERENCES public.beneficiarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_importacoes_beneficiario
    ON public.transacoes_importacao(beneficiario_id);


ALTER TABLE IF EXISTS public.transacoes_importacao
    ADD CONSTRAINT transacoes_importacao_transacao_id_fkey FOREIGN KEY (transacao_id)
    REFERENCES public.transacoes_base (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS transacoes_importacao_pkey
    ON public.transacoes_importacao(transacao_id);


ALTER TABLE IF EXISTS public.usuarios
    ADD CONSTRAINT usuarios_empresa_id_fkey FOREIGN KEY (empresa_id)
    REFERENCES public.empresas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_usuarios_empresa
    ON public.usuarios(empresa_id);

END;