ALTER TABLE empresas
    ADD COLUMN pais VARCHAR(100) NOT NULL,
    ADD COLUMN cep VARCHAR(20) NOT NULL,
    ADD COLUMN cidade VARCHAR(255),
    ADD COLUMN estado VARCHAR(100) NOT NULL;

ALTER TABLE progresso_cadastros
    ADD COLUMN empresa_id UUID UNIQUE REFERENCES empresas(id) ON DELETE CASCADE;
